version: "3"
services:
  clickhouse:
    #  image: clickhouse/clickhouse-server:21.12.4.1
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=NGINXr0cks
    volumes:
      - db-data:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  nms:
    image: ${DOCKER_REGISTRY}/nginx-nms:2.5.1
    ports:
      - "443:443"
    environment:
      - NIM_USERNAME=admin
      - NIM_PASSWORD=nimadmin
      - NIM_LICENSE=${NIM_LICENSE}
      - NIM_CLICKHOUSE_ADDRESS=clickhouse
      - NIM_CLICKHOUSE_PORT=9000
      - NIM_CLICKHOUSE_USERNAME=default
      - NIM_CLICKHOUSE_PASSWORD=NGINXr0cks
    volumes:
      - nms-data:/var/lib/nms

  nginx-plus:
    image: nginxplus-ubuntu:latest
    build: 
      no_cache: true
      context: ./nginx-plus
      secrets:
        - nginx-crt
        - nginx-key
    depends_on:
      - nms
      - echo
    ports:
      - "8080:80"
    secrets:
      - nginx-crt
      - nginx-key
  
  echo:
    image: ealen/echo-server:latest

volumes:
     db-data:
     nms-data:

secrets:
  nginx-crt:
    file: ./nginx-repo.crt
  nginx-key:
    file: ./nginx-repo.key